import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'

const font = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const styles = 'w-[100%] h-auto max-w-[1440px] mx-auto '
 
  return (
    <html lang="en">
      <body className={`${font.className} ${styles} `}>{children}</body>
    </html>
  )
}

